<%@ Page Title="" Language="C#" MasterPageFile="~/Thaitae.Master" AutoEventWireup="true" CodeBehind="ChampionsLeagueFinal.aspx.cs" Inherits="Thaitae.ChampionsLeagueFinal" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
    <style type="text/css">
        ul.team li
        {
            list-style-type: none;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <table width="100%">
        <tr>
            <td>
                <ul class="team">
                    <li>
                        <table>
                            <tr>
                                <td>team1</td>
                                <td>2</td>
                            </tr>
                            <tr>
                                <td>tesm2</td>
                                <td>1</td>
                            </tr>
                        </table>
                    </li>
                    <li>
                        <table>
                            <tr>
                                <td>team1</td>
                                <td>2</td>
                            </tr>
                            <tr>
                                <td>tesm2</td>
                                <td>1</td>
                            </tr>
                        </table>
                    </li>
                    <li>
                        <table>
                            <tr>
                                <td>team1</td>
                                <td>2</td>
                            </tr>
                            <tr>
                                <td>tesm2</td>
                                <td>1</td>
                            </tr>
                        </table>
                    </li>
                    <li>
                        <table>
                            <tr>
                                <td>team1</td>
                                <td>2</td>
                            </tr>
                            <tr>
                                <td>tesm2</td>
                                <td>1</td>
                            </tr>
                        </table>
                    </li>
                    <li>
                        <table>
                            <tr>
                                <td>team1</td>
                                <td>2</td>
                            </tr>
                            <tr>
                                <td>tesm2</td>
                                <td>1</td>
                            </tr>
                        </table>
                    </li>
                    <li>
                        <table>
                            <tr>
                                <td>team1</td>
                                <td>2</td>
                            </tr>
                            <tr>
                                <td>tesm2</td>
                                <td>1</td>
                            </tr>
                        </table>
                    </li>
                    <li>
                        <table>
                            <tr>
                                <td>team1</td>
                                <td>2</td>
                            </tr>
                            <tr>
                                <td>tesm2</td>
                                <td>1</td>
                            </tr>
                        </table>
                    </li>
                    <li>
                        <table>
                            <tr>
                                <td>team1</td>
                                <td>2</td>
                            </tr>
                            <tr>
                                <td>tesm2</td>
                                <td>1</td>
                            </tr>
                        </table>
                    </li>
                    <li>
                        <table>
                            <tr>
                                <td>team1</td>
                                <td>2</td>
                            </tr>
                            <tr>
                                <td>tesm2</td>
                                <td>1</td>
                            </tr>
                        </table>
                    </li>
                </ul>
            </td>
            <td>
                <ul class="team">
                    <li>
                        <table>
                            <tr>
                                <td>team1</td>
                                <td>2</td>
                            </tr>
                            <tr>
                                <td>tesm2</td>
                                <td>1</td>
                            </tr>
                        </table>
                    </li>
                    <li>
                        <table>
                            <tr>
                                <td>team1</td>
                                <td>2</td>
                            </tr>
                            <tr>
                                <td>tesm2</td>
                                <td>1</td>
                            </tr>
                        </table>
                    </li>
                    <li>
                        <table>
                            <tr>
                                <td>team1</td>
                                <td>2</td>
                            </tr>
                            <tr>
                                <td>tesm2</td>
                                <td>1</td>
                            </tr>
                        </table>
                    </li>
                    <li>
                        <table>
                            <tr>
                                <td>team1</td>
                                <td>2</td>
                            </tr>
                            <tr>
                                <td>tesm2</td>
                                <td>1</td>
                            </tr>
                        </table>
                    </li>
                </ul>
            </td>
            <td>
                <ul class="team">
                    <li>
                        <table>
                            <tr>
                                <td>team1</td>
                                <td>2</td>
                            </tr>
                            <tr>
                                <td>tesm2</td>
                                <td>1</td>
                            </tr>
                        </table>
                    </li>
                    <li>
                        <table>
                            <tr>
                                <td>team1</td>
                                <td>2</td>
                            </tr>
                            <tr>
                                <td>tesm2</td>
                                <td>1</td>
                            </tr>
                        </table>
                    </li>
                </ul>
            </td>
            <td>
                <ul class="team">
                    <li>
                        <table>
                            <tr>
                                <td>team1</td>
                                <td>2</td>
                            </tr>
                            <tr>
                                <td>tesm2</td>
                                <td>1</td>
                            </tr>
                        </table>
                    </li>
                </ul>
            </td>
        </tr>
    </table>
</asp:Content>